"""A finding as a first-class record: the number, and everything that
lets a reader re-derive it.

The bar (operator, 2026-09-04): every finding carries a citation, a
provenance and a version — the repo commit that produced it, the exact
command line, the instrument stamp, the stamps of every dataset and
bundle it consumed, the certificate and datasheet files it rests on,
and, for an audit of someone else's code, the version or hash that was
read. Findings live in `docs/findings/<id>.json`, TRACKED, so the paper's
numbers are in the repository even when the runs that produced them are
on a rented machine's volume; `tools/findings.py` renders the ledger.

Stdlib only, like every record an auditor recomputes.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

from rq_pipeline.bundles.json_record import JsonRecord

FINDINGS_DIR = Path("docs") / "findings"
FINDING_FILE = "finding.json"


@dataclass(frozen=True)
class Finding(JsonRecord):
    """One claim with its provenance."""

    id: str  # kebab-case, the file's stem: "demo-count-curve-lift-2026-09-04"
    claim: str  # one sentence, the number in it
    date: str  # ISO day the measurement finished
    repo_commit: str  # git short hash of the tree that ran it
    argv: list[str]  # the command line, verbatim
    instrument: str  # the engine stamp the trials ran on
    outcome: dict[str, Any]  # the numbers: per-arm counts, intervals, effects
    inputs: dict[str, Any] = field(
        default_factory=dict
    )  # dataset/bundle stamps, spec hash
    artifacts: dict[str, str] = field(
        default_factory=dict
    )  # certificate/datasheet paths
    sources: dict[str, str] = field(
        default_factory=dict
    )  # audited externals: name -> version/hash
    protocol: str = ""  # the doc that defines the procedure
    caveats: tuple[str, ...] = ()  # what the number does NOT show

    def __post_init__(self) -> None:
        # JSON has no tuples: a record read back carries lists, and a
        # frozen dataclass compares them unequal to the tuple it wrote.
        object.__setattr__(self, "caveats", tuple(self.caveats))
        object.__setattr__(self, "argv", list(self.argv))

    def path(self, root: Path) -> Path:
        return Path(root) / FINDINGS_DIR / f"{self.id}.json"


def repo_commit(root: Path) -> str:
    """The tree's short hash, with `-dirty` when the tree is not clean:
    a finding from an uncommitted tree says so."""
    head = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    dirty = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return f"{head}-dirty" if dirty else head


def today() -> str:
    return date.today().isoformat()


def load_findings(root: Path) -> list[Finding]:
    """Every tracked finding, newest date first."""
    folder = Path(root) / FINDINGS_DIR
    if not folder.is_dir():
        return []
    found = [Finding.read(p) for p in sorted(folder.glob("*.json"))]
    return sorted(found, key=lambda f: (f.date, f.id), reverse=True)


def render_ledger(findings: list[Finding]) -> str:
    """The ledger page: one section per finding, every provenance field
    stated, nothing summarised away."""
    lines = [
        "# Findings ledger",
        "",
        "Every number here resolves to a commit, a command line, an",
        "instrument stamp and the artifacts it rests on. Generated by",
        "`tools/findings.py` from `docs/findings/*.json`; edit the records,",
        "not this page.",
        "",
    ]
    for f in findings:
        lines += [
            f"## {f.id}",
            "",
            f"**{f.claim}**",
            "",
            f"- date: {f.date} · commit: `{f.repo_commit}`",
            f"- instrument: `{f.instrument}`",
            f"- command: `{' '.join(f.argv)}`",
        ]
        if f.protocol:
            lines.append(f"- protocol: {f.protocol}")
        for label, mapping in (
            ("inputs", f.inputs),
            ("outcome", f.outcome),
            ("artifacts", f.artifacts),
            ("sources", f.sources),
        ):
            if mapping:
                lines.append(f"- {label}:")
                lines += [f"  - {k}: {v}" for k, v in mapping.items()]
        if f.caveats:
            lines.append("- caveats:")
            lines += [f"  - {c}" for c in f.caveats]
        if "figure.png" in f.artifacts:
            lines += ["", f"![{f.id}](../{f.artifacts['figure.png']})"]
        lines.append("")
    return "\n".join(lines)
