[package]
name = "vision"
version = "0.1.0"
edition.workspace = true

[dependencies]
nokhwa = { version = "0.10", features = ["input-native"] }
rerun = "0.35"
anyhow = "1"
usls = { version = "0.2.0-alpha.3", features = ["coreml"] }
sim-core = { version = "0.1.0", path = "../sim-core" }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
