# cargo-about's policy for the Studio's third-party notices: the licences
# accepted here match deny.toml's allow-list. The release workflow runs
# `cargo about generate about.hbs` and ships THIRD_PARTY_LICENSES.md in
# every Studio archive (MIT, BSD and ISC require the notice in binary
# copies; OFL-1.1 requires its licence to travel with the fonts).
accepted = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MIT-0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "ISC",
  "Zlib",
  "BSL-1.0",
  "CC0-1.0",
  "Unlicense",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
  "MPL-2.0",
  "OFL-1.1",
  "Ubuntu-font-1.0",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
