"""Render the STS3215 identifiability matrix as a self-contained figure.

    python3 tools/sts-figure.py            # writes data/sts3215-identifiability.html

The study's punchline — confidently-wrong fits under the wrong register
set, near-perfect recovery with position+load at any rate — had no
visual (the 2026-08-25 demo review's #2 gap). This renders the JSON as
a dependency-free HTML heatmap: rows are rate x corruption, columns
parameters, cells colored by |error| with a hatch where the fit claimed
"pinned" while wrong by more than 10% — the cells that teach the most.
"""

import json
import sys
from html import escape
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "data" / "sts3215-synthetic-identifiability.json"
OUTPUT = REPO / "data" / "sts3215-identifiability.html"

PARAMETERS = ("servo_kp", "damping", "frictionloss", "armature")


def cell_color(error_pct: float) -> str:
    magnitude = min(abs(error_pct), 100.0) / 100.0
    # green (small error) -> red (large), via yellow
    red = int(80 + 175 * min(1.0, magnitude * 2))
    green = int(190 - 150 * max(0.0, magnitude * 2 - 1)) if magnitude > 0.5 else 190
    return f"rgb({red},{green},80)"


def main() -> int:
    study = json.loads(SOURCE.read_text())
    groups: dict[str, list[dict]] = {}
    for condition in study["conditions"]:
        rate, sensors, corruption = condition["label"].split(" ")
        groups.setdefault(sensors, []).append(
            {"rate": rate, "corruption": corruption, **condition}
        )

    rows_html = []
    for sensors in ("pos", "pos+vel", "pos+load", "pos+vel+load"):
        rows_html.append(
            f'<tr><th colspan="{2 + len(PARAMETERS)}" class="group">'
            f"registers fitted: {escape(sensors)}</th></tr>"
        )
        for condition in groups.get(sensors, []):
            cells = [
                f"<td>{escape(condition['rate'])}</td>",
                f"<td>{escape(condition['corruption'])}</td>",
            ]
            for name in PARAMETERS:
                parameter = condition["parameters"][name]
                error = parameter["error_pct"]
                lying = parameter["pinned"] and abs(error) > 10.0
                classes = "lying" if lying else ""
                title = (
                    f"{name}: {parameter['estimate']} "
                    f"(err {error:+.1f}%, "
                    f"{'pinned' if parameter['pinned'] else 'NOT PINNED'})"
                )
                mark = " &#9888;" if lying else ""
                cells.append(
                    f'<td class="{classes}" title="{escape(title)}" '
                    f'style="background:{cell_color(error)}">'
                    f"{error:+.1f}%{mark}</td>"
                )
            rows_html.append("<tr>" + "".join(cells) + "</tr>")

    header = "".join(f"<th>{escape(name)}</th>" for name in PARAMETERS)
    html = f"""<title>STS3215 Identifiability</title>
<style>
  body {{ font: 14px/1.5 -apple-system, system-ui, sans-serif; margin: 2rem;
          background: #fff; color: #1a1a1a; }}
  h1 {{ font-size: 1.3rem; }} .note {{ color: #555; max-width: 46rem; }}
  table {{ border-collapse: collapse; margin-top: 1rem; }}
  th, td {{ padding: 0.35rem 0.7rem; border: 1px solid #ccc; text-align: right; }}
  th {{ background: #f0f0f0; }} th.group {{ text-align: left; background: #e2e8f0; }}
  td.lying {{ outline: 3px solid #b00020; outline-offset: -3px; font-weight: 700; }}
</style>
<h1>STS3215 synthetic identifiability — signed error vs truth</h1>
<p class="note">Each cell: a full <code>mujoco.sysid</code> fit under that
telemetry design. <b>Red-outlined cells claimed "pinned" while wrong by
&gt;10%</b> — confidently-wrong fits, the study's cautionary finding.
The pos+load rows are the protocol verdict: within ~6% at every rate
down to 25&nbsp;Hz. Generated by tools/sts-figure.py from
data/sts3215-synthetic-identifiability.json ({escape(study["design_date"])}).</p>
<table>
<tr><th>rate</th><th>data</th>{header}</tr>
{"".join(rows_html)}
</table>
"""
    OUTPUT.write_text(html)
    print(f"wrote {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
